<?php include 'header.php';?>

    <div class="img-text">Come Experience <br> Canada</div>
    <section id="info">
        <h1 class="upcoming">Upcoming Adventures</h1>
        <h2 class="city-name">Halifax</h2>
        <p class="details">Date: 2017-04-12 <br> Duration: 4 Days</p>
        <h3>Summary</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi!</p>
        <h2 class="city-name">Sydney</h2>
        <p class="details">Date: 2017-05-10 <br> Duration: 2 Days</p>
        <h3>Summary</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta alias ipsum eveniet vel aliquid consequuntur molestiae repellendus atque voluptatibus cumque illum beatae neque autem quasi reiciendis quod, sunt repudiandae eligendi!</p>
    </section>

<?php include 'footer.php';?>